# Generated by Django 2.2.28 on 2024-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insQuire', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slugifiedTitle',
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
