# Generated by Django 2.2.28 on 2024-03-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insQuire', '0006_auto_20240308_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
